### ISSUE TITLE
For Ubuntu 20.04 LTS the docker-cli version doesn't have the docker compose command. 

### ISSUE THREAD

**Issue by caduvieira** [akarzim/zsh-docker-aliases#14]
Maybe support both docker-compose and docker compose while docker-compose isn't deprecated

**Comment by laurentlbm** [comment]
It's still in beta. It is apparently already available on MacOS and Windows, but on Linux, we need to install it manually: https://docs.docker.com/compose/cli-command/

**Comment by akarzim** [comment]
@caduvieira you're right ! I was too enthusiastic ^^'

It is fixed in the last commit (137a5aa) on master.
