### ISSUE TITLE
Handy wrapper for docker-compose exec

### ISSUE THREAD

**Issue by EvgeniyRRU** [akarzim/zsh-docker-aliases#4]
Hello, it's neat zsh-plugin, but what about to add one more thing:
Its common to login into already running container:
```shell
$ docker-compose exec postgres /bin/bash -l
```
May be something like this?
```shell
$ dkclo postgres
```

**Comment by akarzim** [comment]
Hello @EvgeniyRRU, the alias `dkce` already exists so you ca write something like

```sh
$ dkce postgres /bin/bash -l
```

But, you'll agree, it's a non-sense to create an alias for each imaginable command. `/bin/bash` may even not be available for the given container. So if you need to, feel free to create your own alias based on `dkce`.
