### ISSUE TITLE
Commands dont work

### ISSUE THREAD

**Issue by Machine-Maker** [akarzim/zsh-docker-aliases#8]
I cloned the repo into my zsh plugins folder (in this case) ~/.oh-my-zsh/plugins but I get an error saying it couldn't load completions from the zsh-docker-aliases. But that isn't an issue. I add the zsh-docker-aliases to the plugin list in my .zshrc file and source it but None of the commands work.

**Comment by akarzim** [comment]
Support for OhMyZSH has been added thanks to @HenryQW. According to the comments in his PR #5, you need to clone the repo into `~/.oh-my-zsh/custom/plugins`.
